1  AlreadyInitialized
2  Unauthorized
3  ContractPaused
4  TaskNotFound
5  InvalidTaskStatus
6  DeadlinePassed
7  DeadlineNotPassed
8  InvalidReward
9  LockPeriodActive
10 InvalidFeeBps
11 NotTaskOwner
12 NotTaskClaimer
13 NoRewardsAvailable
14 ProofTooLarge
15 NotInitialized
16 TtlTooShort
17 CalldataTooLarge
18 InvalidTaskParams
19 ArithmeticOverflow
20 IncompatibleVerifierInterface
21 BatchTooLarge
22 EmptyBatch
23 BatchRewardCeilingExceeded
